name: Rust

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install necessary packages
      run: |
        sudo apt-get install libasound2-dev
        sudo apt-get install libdbus-1-dev
        sudo apt-get install libpango1.0-dev
        sudo apt-get install libatk1.0-dev
        sudo apt-get install libgdk-pixbuf2.0-dev
        sudo apt-get install libgtk-3-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting
      run: cargo fmt -- --check
